In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
data = {
        'emp_id': [1,2,3,4,5],
        'Gender':['m','f','f','m','f'],
        'remarks':['good','nice','good','great','nice']


}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

   emp_id Gender remarks
0       1      m    good
1       2      f    nice
2       3      f    good
3       4      m   great
4       5      f    nice

In [7]:
categorical_column = df.select_dtypes(include=['object']).columns.tolist()

In [9]:
encoder = OneHotEncoder(sparse_output=False)

In [11]:
one_hot_encoded = encoder.fit_transform(df[categorical_column])

In [14]:

one_hot_df = pd.DataFrame(one_hot_encoded,columns=encoder.get_feature_names_out(categorical_column))

In [16]:
df_encoded = pd.concat([df,one_hot_df],axis=1)

In [18]:
df_encoded = df_encoded.drop(categorical_column,axis=1)

In [19]:
df_encoded

   emp_id  Gender_f  Gender_m  remarks_good  remarks_great  remarks_nice
0       1       0.0       1.0           1.0            0.0           0.0
1       2       1.0       0.0           0.0            0.0           1.0
2       3       1.0       0.0           1.0            0.0           0.0
3       4       0.0       1.0           0.0            1.0           0.0
4       5       1.0       0.0           0.0            0.0           1.0